#!/bin/bash
set -euo pipefail

mkdir -p /root/.ssh
ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null

cd /app
git clone git@github.com:marketplacer/marketplacer.git --depth 1

echo -e "\033[1;32mSchema downloaded!\033[0m"
